#!/bin/bash

git clone https://github.com/eavesmy/flutter_new_web.git
p="flutter_new_web"

if [ ! -d "$HOME/.flutter_web_packages" ];
then
	mkdir $HOME/.flutter_web_packages
fi
rm -rf $HOME/.flutter_web_packages/flutter_web
rm -rf $HOME/.flutter_web_packages/flutter_web_test
rm -rf $HOME/.flutter_web_packages/flutter_web_ui

mv $p/package/* $HOME/.flutter_web_packages/

mv $p/project ./hello_world

echo "
dependency_overrides:
  flutter_web:
    path: "$HOME/.flutter_web_packages/flutter_web"
  flutter_web_ui:
    path: "$HOME/.flutter_web_packages/flutter_web_ui"" >> ./hello_world/pubspec.yaml
	

if [ -n "$1" ];
then
	mv ./hello_world $1
fi

rm -rf $p

echo "Init done."

rm "$0"
